### PR TITLE
[FIX] use absolute path and not resolve to avoid getting into git annex

### LINKED ISSUE #43: eye2bids in datalad run
- When I use `datalad run` to run our converter, the output files are not named as the original edf file but the name from annex is given to the file, e.g., MD5E-s19988724--83aa6a25458ff8b97fdc9cbc1eb6aeac_events.json 
- I do not have asc files saved in my folder after running the converter (usually I do when not using datalad run)

I exectued datalad run like this:
```
datalad run -m "convert edf to bids" \ 
  --input "sourcedata/sub-01/beh/sub-01_taskname.edf" \
  --output "sourcedata/sub-01/beh/sub-01_taskname_events.asc" \
  --output "sourcedata/sub-01/beh/sub-01_taskname_samples.asc" \
  --output "raw/sub-01/beh/sub-01_taskname_events.json" \
  --output "raw/sub-01/beh/sub-01_taskname_eyetrack.json" \
  --output "raw/sub-01/beh/sub-01_taskname_eyetrack.tsv" \
  "eye2bids --input_file sourcedata/sub-01/beh/sub-01_taskname.edf --metadata_file raw/manual_metadata_taskname.yml --output_dir raw/sub-01/beh/ {inputs} {outputs}"
```

### PR DESCRIPTION
**Pull request by Remi-Gau**
closes #43

### CODE REVIEW

**Comment by Remi-Gau** [comment]
@julia-pfarr

**Comment by julia-pfarr** [comment]
Works :-)))))))

**Review by julia-pfarr — APPROVED** [review]

**Comment by Remi-Gau** [comment]
but the tests fail

**Comment by Remi-Gau** [comment]
> but the tests fail

oh that's because the OSF data changed so we need to merge #40 first

**Pull request merged**
